# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-19 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categorias',
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='blog/static/fotos/index.png', upload_to='blog/static/fotos'),
        ),
        migrations.AddField(
            model_name='post',
            name='nombre_imagen',
            field=models.CharField(default='juan.png', max_length=80),
        ),
        migrations.AddField(
            model_name='post',
            name='url_post',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
