# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160819_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default='blog/static/fotos/cambio.jpeg', upload_to='blog/static/fotos'),
        ),
    ]
